export const ADD_ITEM_CART = "ADD_ITEM_CART";
export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const CART_SHIPPING_ADDRESS = "CART_SHIPPING_ADDRESS";
export const CART_PAYMENT_METHOD = "CART_PAYMENT_METHOD";
