export const ITEM_LIST_REQUEST = "ITEM_LIST_REQUEST";
export const ITEM_LIST_SUCCESS = "ITEM_LIST_SUCCESS";
export const ITEM_LIST_ERROR = "ITEM_LIST_ERROR";

export const ITEM_DETAILS_REQUEST = "ITEM_DETAILS_REQUEST";
export const ITEM_DETAILS_SUCCESS = "ITEM_DETAILS_SUCCESS";
export const ITEM_DETAILS_ERROR = "ITEM_DETAILS_ERROR";

export const ITEM_DELETE_REQUEST = "ITEM_DELETE_REQUEST";
export const ITEM_DELETE_SUCCESS = "ITEM_DELETE_SUCCESS";
export const ITEM_DELETE_ERROR = "ITEM_DELETE_ERROR";

export const ITEM_CREATE_REQUEST = "ITEM_CREATE_REQUEST";
export const ITEM_CREATE_SUCCESS = "ITEM_CREATE_SUCCESS";
export const ITEM_CREATE_ERROR = "ITEM_CREATE_ERROR";
export const ITEM_CREATE_RESET = "ITEM_CREATE_RESET";

export const ITEM_UPDATE_REQUEST = "ITEM_UPDATE_REQUEST";
export const ITEM_UPDATE_SUCCESS = "ITEM_UPDATE_SUCCESS";
export const ITEM_UPDATE_ERROR = "ITEM_UPDATE_ERROR";
export const ITEM_UPDATE_RESET = "ITEM_UPDATE_RESET";

export const ITEM_CREATE_REVIEW_REQUEST = "ITEM_CREATE_REVIEW_REQUEST";
export const ITEM_CREATE_REVIEW_SUCCESS = "ITEM_CREATE_REVIEW_SUCCESS";
export const ITEM_CREATE_REVIEW_ERROR = "ITEM_CREATE_REVIEW_ERROR";
export const ITEM_CREATE_REVIEW_RESET = "ITEM_CREATE_REVIEW_RESET";

export const TOP_ITEMS_REQUEST = "TOP_ITEMS_REQUEST";
export const TOP_ITEMS_SUCCESS = "TOP_ITEMS_SUCCESS";
export const TOP_ITEMS_ERROR = "TOP_ITEMS_ERROR";
